name: 1.0$(rev:.r) # build numbering format

trigger: none


resources:
  pipelines:
    - pipeline: ca-pip # Name of the pipeline resource
      source: 02-JassBuddy-Create-Artifacts # Name of the pipeline referenced by the pipeline resource
      trigger: true

pool:
  name: Azure Pipelines
  vmImage: windows-2022

stages:
  - stage: Production
    displayName: "Production"
    jobs:
      - deployment: "DeploymentProduction"
        displayName: "Deployment Production"
        environment: "JassBuddy-Production"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Release_Steps.yaml
